### ISSUE TITLE
Response fields naming rule will be change to Camel case

### ISSUE THREAD

**Issue by kunyan** [redhataccess/hydrajs#28]
I found comment api can not works as expected. I talked with yangli@redhat.com, He said Greg is working on mapping SFDC name to Camel case.

```java
put("commentId","Id");
put("bugzillaCommentId","Bugzilla_Comment__c");
put("caseCommentCreatedDayOfWeek","CaseCommentCreatedDayOfWeek__c")
```

current ts models will be effected

**Comment by engineersamuel** [comment]
Yep, my plan was to change it once the mapping is pushed.

**Comment by engineersamuel** [comment]
Is there any thing we need to do in this issue or can we close it?  I planned on handling this in PCM jira, and regardless we need to completely remove this project from github regardless.
